twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        # point this wherever your images live
        '%kernel.project_dir%/public/images': images
    form_themes:    
            - 'bootstrap_4_layout.html.twig'
            - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

when@test:
    twig:
        strict_variables: true


